name: vivaldi
version: 6.7.3329.39-1
summary: Vivaldi Browser - Feature-packed web browser
description: |
    The web browser for techies and people who need a browser that helps them get things done.
    The user interface is fully customizable, including keyboard shortcuts, mouse gestures, and programmable macros.

    NOTE: This package is maintained by but not yet officially endorsed or supported by Vivaldi Technologies.
confinement: strict
license: Proprietary
type: app
website: https://vivaldi.com
grade: stable
base: core22
icon: vivaldi_icon.png
compression: lzo
adopt-info: vivaldi

# TODO: source-code

# TODO: linter problems

# TODO: Test and fix:
#   * filesystem handling (downloads, etc)
#   * cups/printing
#   * wayland/x11 - support both
#   * secure-storage related stuff
#     - handling of gnome-keyring
#   * policy patch? https://git.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source/tree/build/chromium-patches/snap-policies-path.patch
#   * search engines
#   * usb midi
#   * XDG open handling
#   * Sound
#   * DCONF

apps:
  vivaldi:
    extensions: [gnome]
    command: bin/vivaldi.launcher
    common-id: com.vivaldi.Vivaldi
    desktop: usr/share/applications/vivaldi.desktop
    plugs:
      - audio-playback
      - audio-record
      - bluez # for Web Bluetooth (https://launchpad.net/bugs/1887201)
      - browser-sandbox
      - camera
      - cups
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - mount-observe
      - network
      - network-bind
      - network-manager
      - opengl
      - password-manager-service
      - raw-usb # for WebUSB (https://launchpad.net/bugs/1780678)
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-packages-doc
      - u2f-devices
      - upower-observe
      - wayland
      - x11
    slots:
      - dbus-daemon

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  shmem:
    interface: shared-memory
    private: true
  chromium-ffmpeg-115016:
    interface: content
    target: $SNAP
    default-provider: chromium-ffmpeg

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.vivaldi.vivaldi

parts:
  vivaldi:
    plugin: nil
    after:
      - launcher
    source: https://downloads.vivaldi.com/stable/vivaldi-stable-6.7.3329.39-amd64-binsrc.tar.gz
    source-checksum: sha512/155fb892df5a38a0cee8f81a339c9a101b716fd88ccffeea3fc012bcfaf6891a7e464ac5d233fb725962f17a78533491618d9789408e722f25415f54551b590e
    build-packages:
      - coreutils # for install command
      - sed
    stage-packages:
      - libsecret-1-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcups2
      - libcurl3-gnutls
      - libdbus-1-3
      - libdrm2
      - libexpat1
      - libgbm1
      - libglib2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libu2f-udev
      - libvulkan1
      - libx11-6
      - libxcb1
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxkbcommon0
      - libxrandr2
      - wget
      - xdg-utils
      - libasound2
      - libgl1
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/opt
      mkdir -p $CRAFT_PART_INSTALL/usr

      # install vivaldi data
      cp -r $CRAFT_PART_BUILD/opt/vivaldi $CRAFT_PART_INSTALL/opt

      # install all /usr files from our package as well
      cp -r $CRAFT_PART_BUILD/usr $CRAFT_PART_INSTALL/

      # fix the rights on the sandbox file
      chmod 4755 $CRAFT_PART_INSTALL/opt/vivaldi/vivaldi-sandbox

      # icon path fixup
      sed -i 's|Icon=vivaldi|Icon=usr/share/icons/hicolor/256x256/apps/vivaldi.png|' $CRAFT_PART_INSTALL/usr/share/applications/vivaldi.desktop
    parse-info: [usr/share/appdata/vivaldi.appdata.xml]

  launcher:
    plugin: dump
    source: launcher
    organize:
      '*': bin/
